version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout:  5s
      retries:  5
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dental-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout:  5s
      retries:  10
    networks:
      - dental-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/.env
    networks:
      - dental-network
    depends_on:
      - auth-service
      - notification-service
      - patient-service
# INSERT_NEW_DEPENDENCY_HERE

  auth-service:
    build:
      context: ./services/auth-service
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    env_file:
      - ./services/auth-service/.env
    networks:
      - dental-network
    depends_on:
      postgres:
        condition: service_healthy

  notification-service:
    build:
      context: ./services/notification-service
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    env_file:
      - ./services/notification-service/.env
    networks:
      - dental-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  patient-service:
    build:
      context: ./services/patient-service
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    env_file:
      - ./services/patient-service/.env
    networks:
      - dental-network
    depends_on:
      postgres:
        condition: service_healthy

  agenda-service:
    build:
      context: ./services/agenda-service
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    env_file:
      - ./services/agenda-service/.env
    networks:
      - dental-network
    depends_on:
      postgres:
        condition: service_healthy
# INSERT_NEW_SERVICE_HERE

networks:
  dental-network:
    driver: bridge

volumes:
  pg_data: